### ISSUE TITLE
Delete reply api throws exception

### ISSUE THREAD

**Issue by murrayju** [wannabeCitizen/projectsystem#15]
Sending a `DELETE` to `http://projects.d0ck.me/api/org/2f1141a5-9087-42b7-b3f5-7da3ea880000/idea/75323831-5dd4-4a47-87d6-c9c552a43d5f/comment/0/reply/0` returns a `500 INTERNAL SERVER ERROR` response.

Here is the error response:
```
TypeError

TypeError: delete() got an unexpected keyword argument 'reply_id'

Traceback (most recent call last)

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__

return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app

response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 263, in error_router

return original_handler(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception

reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 260, in error_router

return self.handle_error(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app

response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request

rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 263, in error_router

return original_handler(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception

reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 260, in error_router

return self.handle_error(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request

rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 431, in wrapper

resp = resource(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view

return self.dispatch_request(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 521, in dispatch_request

resp = meth(*args, **kwargs)
TypeError: delete() got an unexpected keyword argument 'reply_id'
```

**Comment by wannabeCitizen** [comment]
I can fix this, but we need to get online together and sort out the running of the app because right now we're developing in 2 runtime environments.  I'm not using Docker w/ the proxy.js since it wasn't working for me.

@murrayju Should we get a stable dev env first and foremost?

**Comment by murrayju** [comment]
Shouldn't be any issues with running the app. Either
1. Run it locally `sudo python manager.py`
2. Run on Vagrant `vagrant up`

I updated the README to reflect this. Docker is kinda working, but not very well at the moment. Vagrant is much easier. Either way, you'll have to add an entry to your hosts file (either localhost, or the ip of the vagrant box).
